SELECT 
    RIDER_ID,
    COUNT(DELIVERED_ORDERS) AS TOTAL_DELIVERIES
FROM BDM.PUBLIC.BIG_DATA_MANAGEMENT
GROUP BY RIDER_ID
ORDER BY TOTAL_DELIVERIES DESC
LIMIT 5;

top_5_riders_with_total_deliveries

SELECT 
    RIDER_ID,
    AVG(DATEDIFF(MINUTE, ORDER_TIME, ACCEPT_TIME)) AS avg_accept_time_minutes
FROM BDM.PUBLIC.BIG_DATA_MANAGEMENT
WHERE ORDER_TIME IS NOT NULL 
  AND ACCEPT_TIME IS NOT NULL 
  AND RIDER_ID IS NOT NULL
GROUP BY RIDER_ID
ORDER BY avg_accept_time_minutes ASC;

average_accept_time_by_each_rider

[10:38 pm, 24/7/2025] +91 95619 72514: SELECT 
    RIDER_ID,
    AVG(DATEDIFF(MINUTE, ACCEPT_TIME, PICKUP_TIME)) AS avg_pickup_time_minutes
FROM BDM.PUBLIC.BIG_DATA_MANAGEMENT
WHERE ACCEPT_TIME IS NOT NULL 
  AND PICKUP_TIME IS NOT NULL 
  AND RIDER_ID IS NOT NULL
GROUP BY RIDER_ID
ORDER BY avg_pickup_time_minutes ASC
LIMIT 10000;


average pickup time by each rider


SELECT 
    RIDER_ID,
    COUNT(*) AS total_undelivered_orders
FROM BDM.PUBLIC.BIG_DATA_MANAGEMENT
WHERE DELIVERED_TIME IS NULL 
  AND RIDER_ID IS NOT NULL
GROUP BY RIDER_ID
ORDER BY total_undelivered_orders DESC;

total undelivered orders
